name: CICD
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
    - name: Install wkhtmltopdf
      run: |
        sudo apt-get install -y xfonts-base xfonts-75dpi
        wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
        sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb
    - uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.x'
    
    - name: debugging
      working-directory: ./cv
      run: |
        sudo apt-get install tree
        tree

    - name: Install go dependencies
      run: go mod download
      working-directory: ./cv
    
    - name: Build CV files
      working-directory: ./cv
      run: | 
        go run generate.go en
        go run generate.go de

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest CV build"
        prerelease: false
        files: |
          ./cv/dist/*.pdf
          ./cv/dist/*.html
