name: CICD
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build CV
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Fonts
        uses: fontist/setup-fontist@v2
      - run: fontist install "Roboto"

      - name: Setup Typst
        uses: typst-community/setup-typst@v3
        id: setup-typst
        env:
          TYPST_FONT_PATHS: "~/.fontist/fonts"
        with:
          cache-dependency-path: |
            cv/en.typ
            cv/de.typ
      - run: typst compile --input LANG=en cv/en.typ DI.Thomas.Schuiki.CV.en.pdf
      - run: typst compile --input LANG=de cv/de.typ DI.Thomas.Schuiki.CV.de.pdf
      #- run: typst compile letter.typ --font-path ./src/fonts

      - name: create release
        uses: "softprops/action-gh-release@v2"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "latest"
          name: "Latest CV build"
          prerelease: false
          files: |
            ./cv/*.pdf
