name: CICD
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.x'

    - name: Install go dependencies
      run: go mod download
      working-directory: ./cv
    
    - name: Build CV files
      working-directory: ./cv
      run: | 
        go run generate.go en
        go run generate.go de

    - name: html to pdf
      uses: fifsky/html-to-pdf-action@master
      with:
        htmlFile: ./cv/dist/index.de.html
        outputFile: ./cv/dist/resume.pdf
        pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest CV build"
        prerelease: false
        files: |
          ./cv/dist/*.pdf
          ./cv/dist/*.html
