name: CICD
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.x'
    - name: Install go dependencies
      run: go mod download
      working-directory: cv
    - name: Build CV files
      run: go run generate.go
      working-directory: cv
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest CV build"
        prerelease: false
        files: |
          ./dist/*
