name: CICD
on:
  push:
    branches:
      - main
jobs:
  build:
    name: compile-check
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Typst
        uses: typst-community/setup-typst@v3
        id: setup-typst
        with:
          cache-dependency-path: cv/cv.typ

      - run: typst compile cv/cv.typ
      #- run: typst compile letter.typ --font-path ./src/fonts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./cv/*.pdf
          if-no-files-found: error
